package com.Miao.community.mapper;

import com.Miao.community.model.CommentLike;
import com.Miao.community.model.CommentLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CommentLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    long countByExample(CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    int deleteByExample(CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    int insert(CommentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    int insertSelective(CommentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    List<CommentLike> selectByExampleWithRowbounds(CommentLikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    List<CommentLike> selectByExample(CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    CommentLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommentLike record, @Param("example") CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    int updateByExample(@Param("record") CommentLike record, @Param("example") CommentLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    int updateByPrimaryKeySelective(CommentLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentlike
     *
     * @mbg.generated Wed Nov 13 17:31:50 CST 2019
     */
    int updateByPrimaryKey(CommentLike record);
}